### ISSUE TITLE
Path to orca job

### ISSUE THREAD

**Issue by sgu800** [SCM-NV/PLAMS#11]
Dear All,

Lately I am having issues with running orca job and find out that it is a problem with defining of path to ORCA. 

Before, .run file for orca has a full path " /hpc/sw/orca-3.0.3/bin/orca a.in" and it worked fine. But now .run file reads like " orca a.in" and I am getting a following error.
"8 total processes failed to start
ORCA finished by error termination in ORCA_GTOInt".

We need to provide full path to orca job to make it work (earlier version is better). Other option is "orca a.in" in .run file can be replaced by "$ORCA_BINDIR/orca".

Kind regards,
Satesh

**Comment by felipeZ** [comment]
The Best solution is to add the following line to your  `$HOME/.bashrc`:
```
alias orca='ORCA_BINDIR/orca'
```

**Comment by felipeZ** [comment]
I used to have the following two lines of code in the [get_runscript](https://github.com/SCM-NV/PLAMS/blob/master/src/scm/plams/interfaces/orca.py#L109) method:
```python
    path = string(subprocess.check_output(['which', 'orca'])).rstrip()
    return '{} {}'.format(path, self._filename('inp'))
```
It seems redundant but if there is another `orca` executable installed in the computer (as it is the case in Cartesius), the orca binary is pointing to the wrong file.

**Comment by h4nsu** [comment]
Doing `which orca` in get_runscript is a bad idea, because many people, while running their scripts on the cluster, tend to load orca module as a prefix to runscript:

`myjob.settings.runscript.pre = "module load orca"`

That way `orca` is not recognized as a valid command at the time `get_runscript()` is called and `which orca` throws an exception.

@sgu800: You need to make sure that `orca` is visible in your environment, for example by adding its location to `PATH` or via the solution Felipe proposed above. You can make this adjustments global, in your `.bashrc` or just for the particular runscript:

orcajob.settings.runscript.pre = 'export PATH=$PATH:/path/to/orca/executable'
