### ISSUE TITLE
Query MultiJob results

### ISSUE THREAD

**Issue by lopeztarifa** [SCM-NV/PLAMS#119]
Dear PLAMS developers, 

I was wondering if I am constructing an AMS MultiJob and results in the right direction: 

```
job1 = AMSJob(molecule=mol, settings=sett)
job2 = AMSJob(molecule=mol, settings=sett2)
job_list=[job1, job2]
multijob=MultiJob()
multijob.children=job_list

# Run job:
results_multijob = multijob.run()
```

If so, how can I query e.g. the results for job1 (with get_energy and the sort)? 
Thanks!

**Comment by patrickmelix** [comment]
You should be able to access the children the same way you defined them. Also you can iterate over `multijob`. If you use a dictonary instead of a list to define the children, retrieving jobs can be a bit better to read. In your case multiple ways should work:
```
job1E = job1.results.get_energy()
job2E = multijob.children[1].results.get_genergy()
energies = [ job.results.get_energy() for job in multijob ]
```

I would suggest to define the children as a dict to make sure you always get the right job:
```
job1 = AMSJob(molecule=mol, settings=sett)
job2 = AMSJob(molecule=mol, settings=sett2)
job_dict = {'job1': job1, 'job2': job2}
...
```

**Comment by lopeztarifa** [comment]
Thanks a lot, @patrickmelix , that works!
