### ISSUE TITLE
No Backwards Compatibility in ADF Interface for KFFiles

### ISSUE THREAD

**Issue by patrickmelix** [SCM-NV/PLAMS#50]
Hey,

in `interfaces/adfsuite/adf.py` in line 140, the code uses the `'General', 'user input'` section to be read for recreation of settings from a t21-File. This section seems to have changed name from the 2017 to 2018 Version of ADF. So no files from previous releases can be read using this method. 

I tried fixing it with an option to read the `'General', 'Input'` (thats the name in 2017) if the above fails, but then there are following errors that I cannot solve ('End missing' even though its there).

Would be helpful to have that changed.
Thanks!
Patrick

**Comment by h4nsu** [comment]
The problem was (apart from a missing import ;P) caused by the fact that previously multiline strings were saved in a really stupid way: a) pad every line with spaces so that its length is 160 b) concatenate all such lines into one single-line string. Don't ask me why...

This commit should in principle resolve that problem. BUT there's a catch. The example file you sent me was generated by an input file in which ancient format was used:
```
restart /home/pmelix/calc/adf/dabco/parametrization/orig/plams.35767/mult/orig-spin4/orig-spin4.t21 &
  nogeo
  spinflip 5
end
```
Our new parser cannot handle that. I don't know how many files like that you have, but I think the only solution for now would be to manually edit the input section of such TAPE21 and fix the input formatting...

**Comment by patrickmelix** [comment]
Thx for the hotfix!

Mmh, I am a bit confused about SCM's policy here then. This way of input was standard until the 2018 release, meaning all input files with restarts will have that. I wouldn't call that 'ancient' ;-) 
If you ask me personally how many it will be for me: Probably a couple of thousand all over my disk...

Since the `load_external` is a new functionality I think its ok to leave it like that in PLAMS. One can load the jobs like this without the settings and a warning to grab results. So I'm fine like that. Even though I am a bit surprised about the inability of AMS2018 to handle old input files, pretty user-unfriendly...

Thanks for your fix!

**Comment by patrickmelix** [comment]
Btw: Will you merge to the master please? :sunglasses:
